from .estado import Estado
from .municipio import Municipio
from .cp import CP
from .colonia import Colonia
from .tipo_hogar import TipoHogar
from .direccion import Direccion
from .rol import Rol
from .institucion import Institucion
from .usuario import Usuario
from .proceso_escalafon import ProcesoEscalafon
from .documents import Document
from .prom import Prom
from .proceso_aprobacion_cursos import ProcesoAprobacionCursos
from .retroalimentacion_ia_curso import RetroalimentacionIaCurso
from .curso import Curso
from .foro import Foro
from .post_foro import PostForo
from .bitacora_evento import BitacoraEvento