# Generated by Django 6.0 on 2026-01-12 04:22

import django.utils.timezone
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id_institucion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=100)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'instituciones',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('rol', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    to='users.rol'
                )),
                ('institucion', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    to='users.institucion'
                )),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]