# Generated by Django 6.0 on 2026-04-17 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10)),
                ("zona", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("embedding", models.JSONField()),
                ("source", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Estado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("clave_estado", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Prom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folio", models.CharField(max_length=50)),
                ("curp", models.CharField(max_length=18)),
                ("nombre", models.CharField(max_length=100)),
                ("primer_apellido", models.CharField(max_length=50)),
                ("segundo_apellido", models.CharField(max_length=50)),
                ("correo1", models.EmailField(max_length=254)),
                ("correo2", models.EmailField(blank=True, max_length=254, null=True)),
                ("telefono1", models.CharField(max_length=15)),
                ("telefono2", models.CharField(blank=True, max_length=15, null=True)),
                ("entidad", models.CharField(max_length=50)),
                ("cct", models.CharField(max_length=50)),
                ("subsistema", models.CharField(max_length=120)),
                ("sistema", models.CharField(max_length=50)),
                ("cargo", models.CharField(max_length=50)),
                ("funcion", models.CharField(max_length=50)),
                ("cargo_val", models.CharField(max_length=50)),
                ("tipo_val", models.CharField(max_length=120)),
                ("estudios_posgrado", models.CharField(max_length=50)),
                ("exp_fds", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="TipoHogar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Colonia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "cp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colonias",
                        to="users.cp",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Municipio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("clave_municipio", models.CharField(max_length=10)),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="municipios",
                        to="users.estado",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cp",
            name="municipio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cps",
                to="users.municipio",
            ),
        ),
        migrations.CreateModel(
            name="ProcesoEscalafon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folio", models.CharField(max_length=50)),
                ("tipo_proceso", models.CharField(max_length=50)),
                ("ciclo_escolar", models.CharField(max_length=20)),
                ("funcion", models.CharField(max_length=100)),
                ("tipo_sostenimiento", models.CharField(max_length=50)),
                ("tipo_valoracion", models.TextField()),
                ("datos_multifactores", models.JSONField()),
                ("estatus", models.CharField(max_length=50)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.estado"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procesos",
                        to="users.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Direccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calle", models.CharField(max_length=150)),
                ("numero_exterior", models.CharField(max_length=20)),
                (
                    "numero_interior",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "colonia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="direcciones",
                        to="users.colonia",
                    ),
                ),
                (
                    "tipo_hogar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.tipohogar",
                    ),
                ),
            ],
        ),
    ]
