# Generated by Django 6.0 on 2026-05-02 01:06

import django.db.models.deletion
from django.db import migrations, models


def crear_tablas_faltantes(apps, schema_editor):
    modelos = [
        'RetroalimentacionIaCurso',
        'ProcesoAprobacionCursos',
        'BitacoraEvento',
        'Curso',
        'Foro',
        'PostForo',
    ]

    with schema_editor.connection.cursor() as cursor:
        tablas_existentes = set(
            schema_editor.connection.introspection.table_names(cursor)
        )

    for nombre_modelo in modelos:
        modelo = apps.get_model('users', nombre_modelo)
        nombre_tabla = modelo._meta.db_table

        if nombre_tabla in tablas_existentes:
            continue

        schema_editor.create_model(modelo)
        tablas_existentes.add(nombre_tabla)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cp_document_estado_prom_tipohogar_colonia_municipio_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='RetroalimentacionIaCurso',
                    fields=[
                        ('id_retroalimentacion', models.AutoField(primary_key=True, serialize=False)),
                        ('sugerencias', models.TextField()),
                        ('confianza_pbt', models.DecimalField(decimal_places=2, max_digits=5)),
                        ('version', models.IntegerField()),
                        ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'verbose_name': 'Retroalimentación IA Curso',
                        'db_table': 'retroalimentacion_ia_curso',
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='BitacoraEvento',
                    fields=[
                        ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                        ('tipo_evento', models.CharField(max_length=50)),
                        ('descripcion', models.TextField()),
                        ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                        ('ip_direccion', models.CharField(blank=True, max_length=50, null=True)),
                        ('detalles', models.JSONField(blank=True, null=True)),
                        ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
                    ],
                    options={
                        'db_table': 'bitacora_eventos',
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Curso',
                    fields=[
                        ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                        ('nombre', models.CharField(max_length=200)),
                        ('descripcion', models.TextField(blank=True, null=True)),
                        ('ciclo_escolar', models.CharField(max_length=20)),
                        ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                        ('activo', models.BooleanField(default=True)),
                        ('docente', models.ForeignKey(db_column='docente_id', on_delete=django.db.models.deletion.CASCADE, related_name='cursos_impartidos', to='users.usuario')),
                        ('institucion', models.ForeignKey(db_column='institucion_id', on_delete=django.db.models.deletion.CASCADE, to='users.institucion')),
                    ],
                    options={
                        'db_table': 'cursos',
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Foro',
                    fields=[
                        ('id_foro', models.AutoField(primary_key=True, serialize=False)),
                        ('titulo', models.CharField(max_length=200)),
                        ('descripcion', models.TextField()),
                        ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                        ('activo', models.BooleanField(default=True)),
                        ('curso', models.ForeignKey(db_column='curso_id', on_delete=django.db.models.deletion.CASCADE, related_name='foros', to='users.curso')),
                    ],
                    options={
                        'db_table': 'foros',
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='PostForo',
                    fields=[
                        ('id_post', models.AutoField(primary_key=True, serialize=False)),
                        ('contenido', models.TextField()),
                        ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                        ('fecha_edicion', models.DateTimeField(auto_now=True)),
                        ('autor', models.ForeignKey(db_column='autor_id', on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
                        ('foro', models.ForeignKey(db_column='foro_id', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='users.foro')),
                    ],
                    options={
                        'db_table': 'posts_foro',
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='ProcesoAprobacionCursos',
                    fields=[
                        ('id_proceso', models.AutoField(db_column='id_proceso', primary_key=True, serialize=False)),
                        ('iteracion', models.CharField(max_length=50)),
                        ('decision', models.CharField(max_length=50)),
                        ('comentarios', models.TextField()),
                        ('fecha_revision', models.DateTimeField()),
                        ('evaluador', models.ForeignKey(db_column='id_evaluador', on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_realizadas', to='users.usuario')),
                    ],
                    options={
                        'db_table': 'proceso_aprobacion_cursos',
                    },
                ),
            ],
        ),
        migrations.RunPython(
            crear_tablas_faltantes,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
