# Generated by Django 6.0 on 2026-05-24 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_contenido_json_curso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'managed': False, 'ordering': ['nombre_rol']},
        ),
        migrations.AddField(
            model_name='procesoaprobacioncursos',
            name='curso',
            field=models.ForeignKey(blank=True, db_column='id_curso', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones', to='users.curso'),
        ),
    ]
